### ISSUE TITLE
No emails in userinfo

### ISSUE THREAD

**Issue by Anna-Livia** [france-connect/identity-provider-example#43]
Hello,
Thank you for your very useful service.

This is what I get from the `userinfo`
```json
{
 "sub": "1e382513f3cb575fd7a95d5a3edd6e99429fbffe1af3446a4a0f2dbf3d92b26av1", 
 "given_name": "Éric Julien",
 "family_name": "MERCIER",
 "preferred_username": "MERCIER",
 "birthdate": "1969-03-17",
 "gender": "male",
 "birthplace": "95277", 
 "birthcountry": "99100"
}

```

It seem to be missing the mandatory `email` attribute.

**Comment by rdubigny** [comment]
Hello !

Thank you for using this service !

Can you check that the `email` scope is within the queried scopes when calling `/api/v1/authorize` ?

**Comment by rdubigny** [comment]
I close this for now. Do not hesitate to open it back if needed.
